name: Governance Workflow

on: [push]

jobs:
  governance:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Execute proposal
      run: npm run executeProposal --proposalId ${{ github.event.inputs.proposalId }}