# Arquivo: 01-workflow-config.yml
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Arquivo: 02-strategy-node.yml
jobs:
    build:
  
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]  # Definindo múltiplas versões do Node.js

# Arquivo: 03-setup-node-cache.yml
steps:
    - uses: actions/checkout@v4  # Baixa o código do repositório
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Cacheando dependências npm para otimizar o tempo de execução

# Arquivo: 04-install-dependencies.yml
- run: npm ci  # Instala as dependências sem modificar o package-lock.json

# Arquivo: 06-run-tests.yml
- run: npm test  # Executa os testes definidos no package.json
